### ISSUE TITLE
Setting gameHandler.myPlayer with teams

### ISSUE THREAD

**Issue by catdong** [akwiat/Sailboat#1]
SailboatClientGamestructure.js line 24 crashes when someone logs off and then logs in
`this["gameStructure"]["gameHandler"].myPlayer = state.entity.children[0].children[frag.specificData];`
- `children[0]` should be team array
- `frag.specificData` increments on every log-on and goes out of bounds after anyone logs off

**Comment by akwiat** [comment]
fixed!
